# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(151415)
$foreground = rgb(F8F8F8)
$color0 = rgb(3C3C3C)
$color1 = rgb(515053)
$color2 = rgb(525154)
$color3 = rgb(6D6B6E)
$color4 = rgb(6D6B6E)
$color5 = rgb(B0B0B1)
$color6 = rgb(B0B0B1)
$color7 = rgb(EDEDED)
$color8 = rgb(A6A6A6)
$color9 = rgb(6C6A6E)
$color10 = rgb(6E6C70)
$color11 = rgb(918F93)
$color12 = rgb(918F93)
$color13 = rgb(EBEBEC)
$color14 = rgb(EBEBEC)
$color15 = rgb(EDEDED)
