# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000000)
$foreground = rgb(F7F7F7)
$color0 = rgb(1B1B1B)
$color1 = rgb(585858)
$color2 = rgb(696969)
$color3 = rgb(7A7A7A)
$color4 = rgb(8B8B8B)
$color5 = rgb(9C9C9C)
$color6 = rgb(ADADAD)
$color7 = rgb(EAEAEA)
$color8 = rgb(A4A4A4)
$color9 = rgb(757575)
$color10 = rgb(8C8C8C)
$color11 = rgb(A2A2A2)
$color12 = rgb(B9B9B9)
$color13 = rgb(D0D0D0)
$color14 = rgb(E7E7E7)
$color15 = rgb(EAEAEA)
