# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000000)
$foreground = rgb(ECE6DD)
$color0 = rgb(000000)
$color1 = rgb(282726)
$color2 = rgb(31302E)
$color3 = rgb(565850)
$color4 = rgb(67665B)
$color5 = rgb(968976)
$color6 = rgb(968976)
$color7 = rgb(DBD3C6)
$color8 = rgb(99938A)
$color9 = rgb(353432)
$color10 = rgb(42413D)
$color11 = rgb(73756B)
$color12 = rgb(898879)
$color13 = rgb(C8B79D)
$color14 = rgb(C8B79D)
$color15 = rgb(DBD3C6)
