# NVIDIA - required for RTX 50 series (open kernel modules)
env = WLR_DRM_NO_ATOMIC,1
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = NVD_BACKEND,direct
env = WLR_NO_HARDWARE_CURSORS,1

# Wayland app compatibility
#env = GDK_BACKEND,wayland,x1,*
env = QT_QPA_PLATFORM,wayland;xcb
#env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# Cursor fix (common NVIDIA issue)
env = WLR_NO_HARDWARE_CURSORS,1


# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Always refer to Hyprland wiki
# https://wiki.hyprland.org/

# Initial boot script enable to apply initial wallpapers, theming, new settings etc.
# suggest not to change this or delete this including deleting referrence file in ~/.config/hypr/.initial_startup_done
# as long as the referrence file is present, this initial-boot.sh will not execute
exec-once = $HOME/.config/hypr/initial-boot.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1  # auth popups (sudo in GUI)
#exec-once = waybar          # taskbar
exec-once = dunst           # notifications
exec-once = nm-applet       # network manager tray
exec-once = blueman-applet  # bluetooth (if needed)
exec-once = hypridle        # idle/lock daemon
exec-once = hyprpaper       # wallpaper

### Sourcing external config files ###
$configs = $HOME/.config/hypr/configs # Default Configs directory path
$UserConfigs = $HOME/.config/hypr/UserConfigs # User Configs directory path

source=$configs/Keybinds.conf # Pre-configured keybinds

# Load defaults, then user additions/overrides
source= $configs/Startup_Apps.conf 
source= $UserConfigs/Startup_Apps.conf

source= $configs/ENVariables.conf # Environment variables (defaults)
source= $UserConfigs/ENVariables.conf # Environment variables (user)

# For laptop related
source= $configs/Laptops.conf 
source= $UserConfigs/Laptops.conf 
source= $UserConfigs/LaptopDisplay.conf 

# Load defaults, then user additions
source= $configs/WindowRules.conf # Window Rules and Layer Rules (defaults)
source= $UserConfigs/WindowRules.conf # Window Rules and Layer Rules (user)

source= $configs/SystemSettings.conf # Default config for hypr 

source= $UserConfigs/UserDecorations.conf # Decorations config file
source= $UserConfigs/UserAnimations.conf # Animation config file
source= $UserConfigs/UserKeybinds.conf # Put your own keybinds here
source= $UserConfigs/UserSettings.conf # Main Hyprland Settings.
source= $UserConfigs/01-UserDefaults.conf # settings for User defaults apps

# nwg-displays
source= $HOME/.config/hypr/monitors.conf
source= $HOME/.config/hypr/workspaces.conf
